namespace Heroes.SDK.Definitions.Enums.Custom
{
    public enum Players : int
    {
        One,
        Two,
        Three,
        Four
    }

   public enum PlayerMode
    {
       Wait = 0x0,
       RocketAccelCharge = 0x1,
       Jumping = 0x2,
       Fall = 0x4,
       Tripping = 0x5,
       SpringLaunched = 0x6,
       PoleLaunched = 0x7,
       PushingSwitch = 0x9,
       Hurt = 0xA,
       Crash = 0xB,
       Running = 0xE,
       JumpDash = 0xF,
       RidingPinballRail = 0x12,
       MovingTowardsPowerCharacter = 0x13,
       SpinningOnPowerCharacter = 0x14,
       AI_TooFar = 0x1A,
       AIMaybe_Returning = 0x1B,
       CanonFired = 0x1C,
       Grinding = 0x1D,
       RainbowRingTrick = 0x1E,
       Grabbing = 0x1F,
       ObjectControl_Spinning = 0x21,
       StandingWithSwitch = 0x22,
       GrabbingOntoSwitch = 0x23,
       SwitchRelease_Maybe = 0x24,
       PullingSwitch = 0x25,
       Captured = 0x26,
       Vanished = 0x27,
       PinballMode = 0x28,
       SpeedFly_Gliding = 0x29,
       Event = 0x2B,
       Dead = 0x2C,
       Fly = 52,
       FlyTired = 53,
       RocketAccelRelease = 0x36,
       Power_Attack1 = 0x38,
       Power_Attack2 = 0x39,
       ThunderShootSpinning = 0x3B,
       LightDash = 0x3D,
       AirPowerAttackSpinMode = 0x3E,
       AirPowerAttackInPosition = 0x3F,
       PinballRelated_apparently = 0x3F,
       AirPowerAttackShot = 0x40,
       Tornado = 0x42,
       Power_Gliding = 0x43,
       WallStand = 0x44,
       WallJump = 0x45,
       Amy_Tornado = 0x48,
       Tails_RingThrow = 0x4B,
       HammerFloat = 77,
       LightSpeedDash = 0x53,
       Kick = 0x54,
       SFA = 0x55,
    };

    public enum PlayerAnim
    {
        Animation_Stand = 0x0,
        Animation_Idle = 0x2,
        Animation_Idle2 = 0x3,
        Motion_Walk = 0x4,
        Motion_Jog = 0x5,
        Motion_Run = 0x6,
        Motion_Rush = 0x7,
        Motion_Dash = 0x8,
        Animation_Roll = 0x9,
        Animation_RollStill_ = 0xA,
        Animation_Launched = 0xB,
        Animation_Falling = 0xC,
        Animation_FallingFast = 0xD,
        Animation_StandingLand = 0xE,
        Animation_StandingLand2 = 0xF,
        Animation_LandWalking = 0x10,
        Animation_SkidStart = 0x11,
        Animation_Skid = 0x12,
        Animation_SkidStop = 0x13,
        Animation_SkidTurnLeftStart = 0x14,
        Animation_SkidTurnLeftStop = 0x15,
        Animation_HurtStart = 0x16,
        Animation_HurtAir = 0x17,
        Animation_HurtGround = 0x18,
        Animation_FanFloat = 0x19,
        Animation_Land_ = 0x1A,
        Animation_TurnAroundLeft = 0x1B,
        Animation_TurnAroundRight = 0x1C,
        Animation_StopNoTurnAround_ = 0x1D,
        Animation_TeamBlast = 0x1F,
        Animation_TeamBlastEnd = 0x20,
        Animation_Push = 0x21,
        Animation_Pull = 0x22,
        Animation_Grab = 0x23,
        Animation_Holding = 0x24,
        Animation_LetGo = 0x25,
        Animation_PushLarge = 0x26,
        Animation_PullLarge = 0x27,
        Animation_GrabLarge = 0x28,
        Animation_HoldingLarge = 0x29,
        Animation_LetGoLarge = 0x2A,
        Animation_2PIntro = 0x2B,
        Animation_2PIntroEnd = 0x2C,
        Animation_2PIntroInactive_ = 0x2D,
        Animation_VictoryPose = 0x2E,
        Animation_VictoryPoseEnd = 0x2F,
        Animation_Captured_ = 0x30,
        Animation_Dead = 0x31,
        Animation_StunnedOrDead2 = 0x32,
        Animation_TripStart = 0x33,
        Animation_Trip = 0x34,
        Animation_TripEnd = 0x35,
        Animation_JumpCurl = 0x36,
        Animation_JumpRoll = 0x37,
        Animation_JumpUncurl = 0x38,
        Animation_JumpFall = 0x39,
        Animation_JumpPad = 0x3B,
        Animation_FlightFormationRelated_ = 0x3C,
        Animation_Hang = 0x3D,
        Animation_Trick = 62,
        Animation_Glide = 0x3F,
        Animation_FlightFormationStill = 0x40,
        Animation_FlightFormationMove = 0x41,
        Animation_FlightFormationRelated = 0x42,
        Animation_FlightFormationRelated2 = 0x43,
        Animation_RollRelated = 0x44,
        Animation_JumpDash = 0x45,
        Animation_OnRail = 0x46,
        Animation_GrindHold = 0x49,
        Animation_GrindStart = 0x4C,
        Animation_GrindEnd = 0x4D,
        Animation_BottomFlyFormationRail = 0x4E,
        Animation_SuperTeamBlastIntro = 0x52,
        Animation_SuperTeamBlast = 0x53,
        Animation_SuperVictoryPose = 0x54,
        Animation_SuperVictoryPoseEnd = 0x55,
        Animation_RingThrow = 0x5A,
        Animation_LightDash = 0x5A,
        Animation_PowerAirAttack = 0x5A,
        Animation_WallStand = 0x5B,
        Animation_PowerAttack = 0x5B,
        Animation_FlyBobsled = 0x5C,
        Animation_WallJump = 0x5C,
        Animation_PowerAttack2 = 0x5C,
        Animation_BackFlip = 0x5D,
        Animation_PowerAttack3Start = 0x5D,
        Animation_SideFlip = 0x5E,
        Animation_PowerAttack3 = 0x5E,
        Animation_BackFlip2 = 0x5F,
        Animation_PowerAttack3End = 0x5F,
        Animation_LeafTornado = 0x60,
        Animation_PowerPunch2 = 0x60,
        Animation_HammerSwingStart = 0x61,
        Animation_PowerPunch3 = 0x61,
        Animation_HammerSwing = 0x62,
        Animation_PowerExtraAttack = 0x62,
        Animation_HammerSwingEnd = 0x63,
        Animation_HammerTornado = 0x64,
        Animation_HammerTornadoEnd = 0x65,
        Animation_HammerFloat = 0x66,
        Animation_PowerBobsled = 0x66,
        Animation_ThrowStar = 0x67,
        Animation_SlideKick = 0x68,
    };

    public enum ENUM_PLAYER_TYPE
    {
        PLAYER_TYPE_SPEED = 0,
        PLAYER_TYPE_FLY = 1,
        PLAYER_TYPE_POWER = 2,
        NUM_PLAYER_TYPE = 3,
    };


}